import { mapPgRelkind, type RelationKind } from '../relation-kind'
import { withClient } from './client'
import { sqlIdent } from './sql'
import type { PoolClient } from './pool'

type ColumnDdlRow = {
  name: string
  type: string
  notNull: boolean
  defaultExpr: string | null
  identity: string
  generated: string
  generatedExpr: string | null
}

type ConstraintDdlRow = {
  name: string
  definition: string
}

function qualifiedRelationName(schema: string, table: string) {
  return schema === 'public' ? sqlIdent(table) : `${sqlIdent(schema)}.${sqlIdent(table)}`
}

function formatColumnDefinition(column: ColumnDdlRow): string {
  const parts: string[] = [sqlIdent(column.name), column.type]
  if (column.generated === 's' && column.generatedExpr) {
    parts.push(`GENERATED ALWAYS AS (${column.generatedExpr}) STORED`)
  } else if (column.identity === 'a') {
    parts.push('GENERATED ALWAYS AS IDENTITY')
  } else if (column.identity === 'd') {
    parts.push('GENERATED BY DEFAULT AS IDENTITY')
  } else if (column.defaultExpr) {
    parts.push(`DEFAULT ${column.defaultExpr}`)
  }
  if (column.notNull) parts.push('NOT NULL')
  return parts.join(' ')
}

function formatConstraint(constraint: ConstraintDdlRow) {
  return `  CONSTRAINT ${sqlIdent(constraint.name)} ${constraint.definition}`
}

function ensureStatementTerminator(statement: string) {
  return statement.trimEnd().endsWith(';') ? statement.trimEnd() : `${statement.trimEnd()};`
}

export function appendDdlStatements(base: string, statements: string[]) {
  if (statements.length === 0) return base
  return [base, ...statements.map(ensureStatementTerminator)].join('\n\n')
}

export function buildCreateTableDdl(
  schema: string,
  table: string,
  columns: ColumnDdlRow[],
  constraints: ConstraintDdlRow[],
  indexes: string[] = []
) {
  const lines = columns.map((column) => `  ${formatColumnDefinition(column)}`)
  for (const constraint of constraints) {
    lines.push(formatConstraint(constraint))
  }
  const createTable = `CREATE TABLE ${qualifiedRelationName(schema, table)} (\n${lines.join(',\n')}\n);`
  return appendDdlStatements(createTable, indexes)
}

export function buildViewDdl(
  schema: string,
  table: string,
  definition: string,
  kind: RelationKind,
  indexes: string[] = []
) {
  const keyword = kind === 'materialized_view' ? 'CREATE MATERIALIZED VIEW' : 'CREATE VIEW'
  const createView = `${keyword} ${qualifiedRelationName(schema, table)} AS\n${definition.trim()};`
  return appendDdlStatements(createView, indexes)
}

async function getRelationKindForDdl(
  client: PoolClient,
  schema: string,
  table: string
): Promise<RelationKind> {
  const sql = `
    select c.relkind
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = $1
      and c.relname = $2
      and c.relkind in ('r', 'v', 'm', 'p', 'f')
    limit 1
  `
  const { rows } = await client.query(sql, [schema, table])
  const relkind = rows[0]?.relkind
  if (!relkind) {
    const error = new Error(`relation '${schema}.${table}' not found`) as Error & { statusCode?: number }
    error.statusCode = 404
    throw error
  }
  return mapPgRelkind(String(relkind))
}

async function getRelationIndexDefinitions(
  client: PoolClient,
  schema: string,
  table: string
): Promise<string[]> {
  const sql = `
    select pg_get_indexdef(ix.oid) as definition
    from pg_class t
    join pg_namespace n on n.oid = t.relnamespace
    join pg_index i on i.indrelid = t.oid
    join pg_class ix on ix.oid = i.indexrelid
    left join pg_constraint c on c.conindid = ix.oid and c.contype in ('p', 'u', 'x')
    where n.nspname = $1
      and t.relname = $2
      and c.oid is null
    order by ix.relname
  `
  const { rows } = await client.query(sql, [schema, table])
  return rows
    .map((row: Record<string, unknown>) => (row.definition ? String(row.definition) : ''))
    .filter((definition) => definition.length > 0)
}

async function getViewDefinition(client: PoolClient, schema: string, table: string, kind: RelationKind) {
  if (kind === 'materialized_view') {
    const { rows } = await client.query(
      `select definition from pg_catalog.pg_matviews where schemaname = $1 and matviewname = $2`,
      [schema, table]
    )
    return rows[0]?.definition ? String(rows[0].definition) : null
  }

  const { rows } = await client.query(
    `select definition from pg_catalog.pg_views where schemaname = $1 and viewname = $2`,
    [schema, table]
  )
  return rows[0]?.definition ? String(rows[0].definition) : null
}

async function getTableDdlWithClient(client: PoolClient, schema: string, table: string): Promise<string> {
  const kind = await getRelationKindForDdl(client, schema, table)
  if (kind === 'view' || kind === 'materialized_view') {
    const definition = await getViewDefinition(client, schema, table, kind)
    if (!definition) {
      const error = new Error(`definition for '${schema}.${table}' not found`) as Error & {
        statusCode?: number
      }
      error.statusCode = 404
      throw error
    }
    const indexes = await getRelationIndexDefinitions(client, schema, table)
    return buildViewDdl(schema, table, definition, kind, indexes)
  }

  const columnsSql = `
    select
      a.attname as name,
      pg_catalog.format_type(a.atttypid, a.atttypmod) as type,
      a.attnotnull as not_null,
      pg_get_expr(ad.adbin, ad.adrelid) as default_expr,
      coalesce(a.attidentity, '') as identity,
      coalesce(a.attgenerated, '') as generated,
      case
        when a.attgenerated = 's' then pg_get_expr(ad.adbin, ad.adrelid)
        else null
      end as generated_expr
    from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
    where n.nspname = $1
      and c.relname = $2
      and c.relkind in ('r', 'p', 'f')
      and a.attnum > 0
      and not a.attisdropped
    order by a.attnum
  `
  const constraintsSql = `
    select
      c.conname as name,
      pg_get_constraintdef(c.oid, true) as definition
    from pg_constraint c
    join pg_class cl on cl.oid = c.conrelid
    join pg_namespace n on n.oid = cl.relnamespace
    where n.nspname = $1
      and cl.relname = $2
      and c.contype in ('p', 'f', 'u', 'c')
    order by
      case c.contype when 'p' then 1 when 'f' then 2 when 'u' then 3 else 4 end,
      c.conname
  `

  const [{ rows: columnRows }, { rows: constraintRows }, indexes] = await Promise.all([
    client.query(columnsSql, [schema, table]),
    client.query(constraintsSql, [schema, table]),
    getRelationIndexDefinitions(client, schema, table),
  ])

  if (columnRows.length === 0) {
    const error = new Error(`relation '${schema}.${table}' has no columns`) as Error & { statusCode?: number }
    error.statusCode = 404
    throw error
  }

  const columns: ColumnDdlRow[] = columnRows.map((row: Record<string, unknown>) => ({
    name: String(row.name),
    type: String(row.type),
    notNull: Boolean(row.not_null),
    defaultExpr: row.default_expr ? String(row.default_expr) : null,
    identity: String(row.identity || ''),
    generated: String(row.generated || ''),
    generatedExpr: row.generated_expr ? String(row.generated_expr) : null,
  }))
  const constraints: ConstraintDdlRow[] = constraintRows.map((row: Record<string, unknown>) => ({
    name: String(row.name),
    definition: String(row.definition),
  }))

  return buildCreateTableDdl(schema, table, columns, constraints, indexes)
}

export async function getTableDdl(
  connectionName: string | undefined,
  schema: string,
  table: string
): Promise<string> {
  return withClient(connectionName, async (client) => getTableDdlWithClient(client, schema, table))
}
