import { describe, expect, it } from 'vitest'
import { appendDdlStatements, buildCreateTableDdl, buildViewDdl } from '../lib/db/table-ddl'

describe('table-ddl', () => {
  it('builds CREATE TABLE with primary and foreign key constraints', () => {
    const ddl = buildCreateTableDdl(
      'public',
      'orders',
      [
        {
          name: 'id',
          type: 'integer',
          notNull: true,
          defaultExpr: null,
          identity: 'd',
          generated: '',
          generatedExpr: null,
        },
        {
          name: 'user_id',
          type: 'integer',
          notNull: false,
          defaultExpr: null,
          identity: '',
          generated: '',
          generatedExpr: null,
        },
      ],
      [
        { name: 'orders_pkey', definition: 'PRIMARY KEY (id)' },
        {
          name: 'orders_user_id_fkey',
          definition: 'FOREIGN KEY (user_id) REFERENCES users(id)',
        },
      ]
    )

    expect(ddl).toContain('CREATE TABLE "orders" (')
    expect(ddl).toContain('"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL')
    expect(ddl).toContain('CONSTRAINT "orders_pkey" PRIMARY KEY (id)')
    expect(ddl).toContain('CONSTRAINT "orders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id)')
  })

  it('appends CREATE INDEX statements after CREATE TABLE', () => {
    const ddl = buildCreateTableDdl(
      'public',
      'orders',
      [
        {
          name: 'id',
          type: 'integer',
          notNull: true,
          defaultExpr: null,
          identity: '',
          generated: '',
          generatedExpr: null,
        },
      ],
      [{ name: 'orders_pkey', definition: 'PRIMARY KEY (id)' }],
      ['CREATE INDEX orders_created_at_idx ON public.orders USING btree (created_at)']
    )

    expect(ddl).toContain('CREATE TABLE "orders"')
    expect(ddl).toContain(
      'CREATE INDEX orders_created_at_idx ON public.orders USING btree (created_at);'
    )
  })

  it('builds CREATE VIEW DDL with indexes', () => {
    const ddl = buildViewDdl(
      'app',
      'active_users',
      'select id from users where active',
      'materialized_view',
      ['CREATE INDEX active_users_id_idx ON app.active_users USING btree (id)']
    )
    expect(ddl).toContain('CREATE MATERIALIZED VIEW "app"."active_users" AS')
    expect(ddl).toContain('CREATE INDEX active_users_id_idx ON app.active_users USING btree (id);')
  })

  it('appendDdlStatements leaves base unchanged when empty', () => {
    expect(appendDdlStatements('CREATE TABLE "t" ();', [])).toBe('CREATE TABLE "t" ();')
  })
})
